basePath: events
definitions:
  application.EventsOutputDTO:
    properties:
      created_at:
        type: string
      currency:
        type: string
      description:
        type: string
      event_date:
        type: string
      id:
        type: integer
      image_url:
        type: string
      name:
        type: string
      price:
        type: number
      updated_at:
        type: string
    type: object
  application.InputRegisterEventDTO:
    properties:
      currency:
        type: string
      description:
        type: string
      event_date:
        type: string
      image_url:
        type: string
      name:
        type: string
      price:
        type: number
    type: object
  application.InputUpdateEventDTO:
    properties:
      currency:
        type: string
      description:
        type: string
      event_date:
        type: string
      image_url:
        type: string
      name:
        type: string
      price:
        type: number
    type: object
  application.OutputGetEventsDTO:
    properties:
      events:
        items:
          $ref: '#/definitions/application.EventsOutputDTO'
        type: array
      pagination:
        $ref: '#/definitions/pagination.Pagination'
    type: object
  domain.Event:
    properties:
      created_at:
        type: string
      currency:
        type: string
      description:
        type: string
      event_date:
        type: string
      id:
        type: integer
      image_url:
        type: string
      name:
        type: string
      price:
        type: number
      updated_at:
        type: string
    type: object
  pagination.Pagination:
    properties:
      page:
        type: integer
      size:
        type: integer
      total:
        type: integer
      totalPages:
        type: integer
    type: object
host: localhost:3001/
info:
  contact: {}
  description: api to manager events
  title: Events API
  version: "1.0"
paths:
  /:
    get:
      consumes:
      - application/json
      description: list events
      parameters:
      - default: 1
        description: Page number
        in: query
        name: page
        type: integer
      - default: 10
        description: Page size
        in: query
        name: size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/application.OutputGetEventsDTO'
        "500":
          description: Internal Server Error
      security:
      - BearerAuth: []
  /{id}:
    get:
      consumes:
      - application/json
      description: get a event by id
      parameters:
      - description: event id
        format: uuid
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Event'
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      security:
      - BearerAuth: []
  /admin/:
    post:
      consumes:
      - application/json
      description: register a new event
      parameters:
      - description: event request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/application.InputRegisterEventDTO'
      produces:
      - application/json
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      security:
      - BearerAuth: []
  /admin/{id}:
    delete:
      consumes:
      - application/json
      description: remove a event by id
      parameters:
      - description: event id
        format: uuid
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      security:
      - BearerAuth: []
    put:
      consumes:
      - application/json
      description: update a event
      parameters:
      - description: event id
        format: uuid
        in: path
        name: id
        required: true
        type: string
      - description: event request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/application.InputUpdateEventDTO'
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      security:
      - BearerAuth: []
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
