services:
  mongo-database:
    image: mongo:7.0.2
    restart: on-failure
    container_name: mongo_database
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    ports:
      - "27017:27017"
    volumes:
      - mongo-database:/data/db
    env_file: .env

  postgres-database:
    image: postgres:16.0
    container_name: postgres_database
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres-database:/data/postgres
      - ./sql/init_postgres.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    restart: on-failure
  
  mysql-database:
    image: mysql:9.0.0
    container_name: mysql_database
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    volumes:
      - mysql-database:/var/lib/mysql

  rabbitmq-queue:
    image: rabbitmq:3.13.4-management
    container_name: rabbitmq_queue
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: on-failure
    volumes:
      - rabbitmq-queue:/var/lib/rabbitmq

  users-service:
    # image: janapc0/users-services
    build:
      context: ./users
      dockerfile: Dockerfile
    command: npm run start
    depends_on:
      - mongo-database
    container_name: users_services
    ports:
      - "3000:3000"

  events-service:
    # image: janapc0/events-services
    build:
      context: ./events
      dockerfile: Dockerfile
    depends_on:
      - postgres-database
    container_name: events_services
    ports:
      - "3001:3001"

  marketing-service:
    # image: janapc0/marketing-services
    build:
      context: ./marketing
      dockerfile: Dockerfile
    command: npm run start
    depends_on:
      mysql-database: 
        condition: service_healthy
      rabbitmq-queue:
        condition: service_started
    container_name: marketing_services
    ports:
      - "3002:3002"

volumes:
  mongo-database: {}
  postgres-database: {}
  mysql-database: {}
  rabbitmq-queue: {}