services:
  mongo-database:
    image: mongo:7.0.2
    restart: on-failure
    container_name: mongo_database
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    ports:
      - "27017:27017"
    volumes:
      - mongo-database:/data/db
    env_file: .env

  postgres-database:
    image: postgres:16.0
    container_name: postgres_database
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres-database:/data/postgres
      - ./sql/init_postgres.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    restart: on-failure

  users-service:
    image: users-services
    build:
      context: ./users
      dockerfile: Dockerfile
    command: npm run start
    depends_on:
      - mongo-database
    container_name: users_services
    ports:
      - "3000:3000"

  events-service:
    image: events-services
    build:
      context: ./events
      dockerfile: Dockerfile
    depends_on:
      - postgres-database
    container_name: events_services
    ports:
      - "3001:3001"

volumes:
  mongo-database: {}
  postgres-database: {}