services:
  mongodb:
    image: mongo:7.0.2
    restart: on-failure
    container_name: mongodb_event_tickets
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db
    env_file: .env

volumes:
  mongodb: {}