basePath: /
definitions:
  application.InputSaveClient:
    properties:
      email:
        type: string
      name:
        type: string
    type: object
  application.OutputGetClientByEmail:
    properties:
      created_at:
        type: string
      email:
        type: string
      id:
        type: string
      name:
        type: string
    type: object
  application.OutputSaveClient:
    properties:
      created_at:
        type: string
      email:
        type: string
      id:
        type: string
      name:
        type: string
    type: object
host: localhost:3004
info:
  contact: {}
  description: Api to manager clients
  title: Client API
  version: "1.0"
paths:
  /clients:
    get:
      consumes:
      - application/json
      description: get a client by email
      parameters:
      - description: email
        format: email
        in: query
        name: email
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/application.OutputGetClientByEmail'
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
    post:
      consumes:
      - application/json
      description: register a new client
      parameters:
      - description: client request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/application.InputSaveClient'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/application.OutputSaveClient'
        "400":
          description: Bad Request
        "409":
          description: Conflict
        "500":
          description: Internal Server Error
swagger: "2.0"
