receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  otlp/jaeger:
    endpoint: jaeger:4317
    tls:
      insecure: true
  otlphttp/apm:
    endpoint: http://apm_server:8200
    tls:
      insecure: true
  prometheus:
    endpoint: 0.0.0.0:9090
service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp/jaeger, otlphttp/apm]
    metrics:
      receivers: [otlp]
      exporters: [prometheus]
