services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - .docker/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - users-network
    depends_on:
      - app
  app:
    build: .
    container_name: app
    ports:
      - '3000'
    env_file:
      - .env.production
    depends_on:
      - mongodb
      - prometheus
      - grafana
      - jaegertracing
    networks:
      - users-network
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=/run/secrets/mongodb_username
      - MONGO_INITDB_ROOT_PASSWORD=/run/secrets/mongodb_password
    volumes:
      - mongodb_data:/data/db
    networks:
      - users-network
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
      - .docker/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - users-network
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - '3001:3000'
    environment:
      - GF_SECURITY_ADMIN_USER=/run/secrets/grafana_user
      - GF_SECURITY_ADMIN_PASSWORD=/run/secrets/grafana_password
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - users-network
  jaegertracing:
    image: jaegertracing/all-in-one:latest
    ports:
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 4317:4317
      - 4318:4318
      - 14250:14250
      - 14268:14268
      - 14269:14269
      - 9411:9411
    networks:
      - users-network
volumes:
  mongodb_data:
  grafana_data:
  prometheus_data:

networks:
  users-network:

secrets:
  mongodb_username:
    file: .docker/secrets/mongodb_username
  mongodb_password:
    file: .docker/secrets/mongodb_password
  grafana_user:
    file: .docker/secrets/grafana_user
  grafana_password:
    file: .docker/secrets/grafana_password
