services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - .docker/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - users-network
    depends_on:
      - app
  app:
    build: .
    container_name: app
    ports:
      - '3000'
    env_file:
      - .env.production
    depends_on:
      - mongodb
      - prometheus
      - grafana
      - jaegertracing
    networks:
      - users-network
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD_FILE=/run/secrets/mongodb_password
    volumes:
      - mongodb_data:/data/db
    networks:
      - users-network
    secrets:
      - mongodb_password
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
      - .docker/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - users-network
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - '3001:3000'
    environment:
      - GF_SECURITY_ADMIN_USER__FILE=/run/secrets/grafana_user
      - GF_SECURITY_ADMIN_PASSWORD__FILE=/run/secrets/grafana_password
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - users-network
    secrets:
      - grafana_user
      - grafana_password
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - '16686:16686'
      - '4317'
    networks:
      - users-network
  collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: collector
    command: ['--config=/etc/otel-collector-config.yml']
    volumes:
      - .docker/otel-collector-config.yaml:/etc/otel-collector-config.yml
    ports:
      - 4318:4318
      - 4317:4317
    restart: always
    depends_on:
      jaeger:
        condition: service_started
    networks:
      - users-network
volumes:
  mongodb_data:
  grafana_data:
  prometheus_data:
  app_logs:

networks:
  users-network:

secrets:
  mongodb_password:
    file: .docker/secrets/mongodb_password.txt
  grafana_user:
    file: .docker/secrets/grafana_user.txt
  grafana_password:
    file: .docker/secrets/grafana_password.txt
