name: users
services:
  mongo_database:
    image: mongo:7.0.2
    restart: unless-stopped
    container_name: mongo_database
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    ports:
      - "27017:27017"
    volumes:
      - mongo_storage:/data/db
    env_file: .env

  users_service:
    build:
      context: ../
      dockerfile: Dockerfile
    command: npm run start
    depends_on:
      - mongo_database
    container_name: users_service
    ports:
      - "3000:3000"
  
  grafana_monitor:
    image: grafana/grafana-oss:11.2.0
    container_name: grafana_monitor
    restart: unless-stopped
    environment:
      - GF_SERVER_HTTP_PORT=9000
    ports:
     - '9000:9000'
    volumes:
     - 'grafana_storage:/var/lib/grafana'
  
  prometheus_metrics:
    image: prom/prometheus:v2.54.1
    user: root
    container_name: prometheus_metrics
    restart: unless-stopped
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_storage:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - 9090:9090

volumes:
  mongo_storage: {}
  prometheus_storage: {}
  grafana_storage: {}
