name: Events-service

on:
  push:
    branches:
      - main
    paths:
      - "events/**"
env:
  dir: "events"
  go: "1.22.x"

defaults:
  run:
    working-directory: ${{env.dir}}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
          cache-dependency-path: "**/go.sum"
      - name: Verify dependencies
        run: go mod verify
      - name: Build project
        run: go build -v ./...
      - name: Run vet
        run: go vet ./...
      - name: Run staticcheck
        uses: dominikh/staticcheck-action@v1
        with:
          version: "latest"
          install-go: false
          working-directory: ${{ matrix.dir }}
      - name: Install go lint
        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.58.0
      - name: Run lint
        run: golangci-lint run ./...
      - name: Run tests
        run: go test ./...
