name: Events-service

on: [push]
defaults:
  run:
    working-directory: events
jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        go: ["1.22.x"]
        dir: ["events"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
          cache-dependency-path: "**/go.sum"

      - name: Verify dependencies
        run: go mod verify
      - name: Build
        run: go build -v ./...
      - name: Run go vet
        run: go vet ./...
      - name: Run staticcheck
        uses: dominikh/staticcheck-action@v1
        with:
          version: "latest"
          install-go: false
          working-directory: ${{ matrix.dir }}
      - name: Install golint
        run: go install golang.org/x/lint/golint@latest
      - name: Run golint
        run: golint ./...
      - name: Run tests
        run: go test -race -vet=off ./... -json > TestResults.json
      - name: Upload Go test results
        uses: actions/upload-artifact@v4
        with:
          name: Go-results
          path: TestResults.json
