name: golang-services

on:
  push:
    branches:
      - main
    paths:
      - "events/**"
      - "clients/**"

env:
  GO_VERSION: "1.22.x"

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix: { dir: ["events", "clients"] }
    defaults:
      run:
        working-directory: ${{ matrix.dir }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache-dependency-path: "**/go.sum"
      - name: Install Dependencies
        run: go mod download
      - name: Verify Dependencies
        run: go mod verify
      - name: Run vet
        run: go vet ./...
      - name: Run staticcheck
        uses: dominikh/staticcheck-action@v1
        with:
          version: "latest"
          install-go: false
          working-directory: ${{ matrix.dir }}
      - name: Install go lint
        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.58.0
      - name: Run lint
        run: golangci-lint run ./...
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix: { dir: ["events", "clients"] }
    defaults:
      run:
        working-directory: ${{ matrix.dir }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache-dependency-path: "**/go.sum"
      - name: Install Dependencies
        run: go mod download
      - name: Verify Dependencies
        run: go mod verify
      - name: Build project
        run: go build -v ./...
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix: { dir: ["events", "clients"] }
    defaults:
      run:
        working-directory: ${{ matrix.dir }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache-dependency-path: "**/go.sum"
      - name: Install Dependencies
        run: go mod download
      - name: Verify Dependencies
        run: go mod verify
      - name: Run tests
        run: go test -v ./...
